# Generated by Django 3.1.3 on 2022-02-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220130_2109'),
        ('common', '0002_auto_20220131_1554'),
    ]

    operations = [
    ]
