# Generated by Django 4.0.2 on 2022-02-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_merge_20220131_1826'),
        ('common', '0003_merge_20220207_1447'),
    ]

    operations = [
    ]
