# Generated by Django 3.1.3 on 2022-01-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnormal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
