# Generated by Django 3.1.2 on 2022-01-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20220130_2109'),
        ('proj', '0002_auto_20220130_2111'),
        ('proj', '0002_auto_20220131_1554'),
    ]

    operations = [
    ]
