# Generated by Django 3.1.3 on 2022-01-26 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0002_automobile_bus_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automobile',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterField(
            model_name='post_normal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply_normal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluate_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
