# Generated by Django 3.1.3 on 2022-01-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proj', '0003_auto_20220126_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_evaluate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluate_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply_normal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
