# Generated by Django 3.1.3 on 2022-02-07 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_merge_20220207_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post_e', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.post_evaluate')),
                ('post_n', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proj.post_normal')),
            ],
        ),
    ]
