# Generated by Django 4.0.2 on 2022-02-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_merge_0003_merge_20220131_1826_0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
