# Generated by Django 3.1.3 on 2022-01-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_auto_20220126_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_normal',
            name='author',
        ),
    ]
