# Generated by Django 3.1.3 on 2022-01-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_remove_post_normal_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_evaluate',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post_normal',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post_evaluate',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post_normal',
            name='modify_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
