# Generated by Django 3.1.3 on 2022-01-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0007_auto_20220129_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_evaluate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post_normal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
